LWC/Logistic/force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LWC/Logistic/force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>place</fullName>
            </value>
            <value>
                <fullName>ontheway</fullName>
            </value>
            <value>
                <fullName>shipped</fullName>
            </value>
            <value>
                <fullName>delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LWC/Logistic/force-app/main/default/classes/GenerateInvoice.cls
public class GenerateInvoice {
 public Id invoiceId {get;set;}
  
  public List<SelectOption> invoices {
    get {
      if (invoices == null) {
        invoices = new List<SelectOption>();
        for(Invoice__c invoice : [SELECT Id,Name FROM Invoice__c WHERE Status__c = 'placed']){

            invoices.add(new SelectOption(invoice.Id,invoice.Name));
        }	
      }
      return invoices;
    }
    set;
  }
    
    public PageReference sendPdf() {
    
   		PageReference pdf = Page.PdfGeneratorTemplate;
    	// add parent id to the parameters for standardcontroller
    	pdf.getParameters().put('id',invoiceId);
        return pdf;
    }
}