LWC/Logistic/force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LWC/Logistic/force-app/main/default/objects/Invoice__c/fields/ItemName__c.field-meta.xml
<CustomField>
    <fullName>ItemName__c</fullName>
    <label>ItemName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

LWC/Logistic/force-app/main/default/objects/Invoice__c/fields/ShippingDateTime__c.field-meta.xml
<CustomField>
    <fullName>ShippingDateTime__c</fullName>
    <label>ShippingDateTime</label>
    <type>DateTime</type>
</CustomField>

LWC/Logistic/force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>place</fullName>
            </value>
            <value>
                <fullName>ontheway</fullName>
            </value>
            <value>
                <fullName>shipped</fullName>
            </value>
            <value>
                <fullName>delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LWC/Logistic/force-app/main/default/objects/Invoice__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <label>Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

LWC/Logistic/force-app/main/default/classes/AssetController.cls
public class AssetController {
    
    @AuraEnabled(cacheable=true)
    public static List<Invoice__c> getAsset() {
        return [SELECT Id, Name, ItemName__c, Weight__c,
        Mobile__c, Status__c, Total__c, ShippingDateTime__c
            FROM Invoice__c];
    }

    @AuraEnabled(cacheable=true)  
    public static List<sobject> findRecords(String searchKey, String objectName) {  
     string searchText = '\'' + String.escapeSingleQuotes(searchKey) + '%\'';  
     string query = 'SELECT Id, Name FROM ' +objectName+ ' WHERE Name LIKE '+searchText+' LIMIT 6';  
     return Database.query('SELECT Id, Name FROM ' +objectName+ ' WHERE Name LIKE '+searchText+' LIMIT 6');  
   } 
}