LWC/Logistic/force-app/main/default/objects/Cities__c/Cities__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>Cities Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LWC/Logistic/force-app/main/default/objects/Quotation__c/Quotation__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LWC/Logistic/force-app/main/default/objects/Quotation__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <label>Document</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

LWC/Logistic/force-app/main/default/objects/Quotation__c/fields/Parcel__c.field-meta.xml
<CustomField>
    <fullName>Parcel__c</fullName>
    <label>Parcel</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

LWC/Logistic/force-app/main/default/classes/QuotationController.cls
public class QuotationController {
    
    @AuraEnabled(Cacheable=true)
     public static Cities__c[] getAllName() {

       return [SELECT Name FROM Cities__c];

    }

    @AuraEnabled(Cacheable=true)
    public static String getQuotationParcel(String name) {
        String qoutename = name ; 
        String parcel;
        List<Quotation__c> list_qoute = [SELECT Parcel__c FROM Quotation__c WHERE Name LIKE : qoutename];
        for(Quotation__c q : list_qoute){
            parcel = q.Parcel__c;
        }
        
        return parcel;
    }

    @AuraEnabled(Cacheable=true)
    public static String getQuotationDocument(String name) {
        String qoutename = name ; 
        String document;
        List<Quotation__c> list_qoute = [SELECT Document__c FROM Quotation__c WHERE Name LIKE : qoutename];
        for(Quotation__c q : list_qoute){
            document = q.Document__c;
        }
        
        return document;
    }




}